# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/9aaac705-2737-4222-9887-51131acec90c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/afbb025b-f483-4b79-9702-645cfca09e8b";
      fsType = "ext4";
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/5E49-BE19";
      fsType = "vfat";
      options = [ "fmask=0137" "dmask=0027" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@var_cache" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@var_log" ];
    };

  fileSystems."/var/spool" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@var_spool" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@var_tmp" ];
    };

  fileSystems."/var/lib/machines" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@var_lib_machines" ];
    };

  fileSystems."/var/lib/portables" =
    { device = "/dev/disk/by-uuid/9d76cce0-7e9a-4828-8de2-aab9e07badae";
      fsType = "btrfs";
      options = [ "subvol=@var_lib_portables" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp131s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp132s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
